# Generated by Django 4.2.1 on 2023-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_truckmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='reg_number',
            field=models.CharField(max_length=100, verbose_name='Бортовой номер'),
        ),
    ]
